"""
AEGIS-SWARM Razorpay Edition :: Risk / Detector Schema
=========================================================
Output contract for the Detector stage. Reuses the AEGIS-SWARM v1
design principle from agents/risk.py: threat_level (here risk_level) is
a Literal, not a free string, so neither the ML model wrapper nor an
LLM-based detector can emit an invented tier outside the four the
Policy Gate knows how to route.

WHY risk_score AND risk_level BOTH EXIST (design decision):
risk_score is the continuous probability the baseline model or the
Detector's reasoning implies (0.0-1.0) -- useful for calibration,
ROC/PR curves, and threshold tuning during evaluation. risk_level is
the discretized bucket the rest of the pipeline (Investigator, Critic,
Policy Gate) actually reasons over. Keeping both means the Policy Gate
can be recalibrated by moving score thresholds without touching any
agent's prompt or logic.

WHY THE DETECTOR DOES NOT DECIDE THE ACTION (carried over from AEGIS
v1's Scout/Risk separation principle):
Exactly the same reasoning as v1's docstring for scout.py: mixing
detection with the final action in one component makes the reasoning
unauditable and removes the ability to independently challenge it.
"""

from typing import Literal
from pydantic import BaseModel, Field

RiskLevel = Literal["LOW", "MEDIUM", "HIGH", "CRITICAL"]


class DetectorOutput(BaseModel):
    """
    - risk_score: continuous fraud probability from the baseline model
      (0.0-1.0). This is a genuine model output, not an LLM guess --
      see app/models/baseline.py.
    - risk_level: discretized bucket derived from risk_score via fixed,
      documented thresholds (see policy/gate.py THRESHOLDS) -- NOT
      re-invented per-transaction by an LLM.
    - fraud_hypothesis: a one-sentence, evidence-citing explanation of
      why this transaction looks risky (or doesn't). Generated by the
      Detector agent (LLM) from the model's score + raw signal values,
      but the score itself always comes from the trained model.
    - signals: the specific transaction fields that drove the score up,
      surfaced explicitly for auditability (a judge/analyst should be
      able to see exactly what the model reacted to).
    """
    transaction_id: str
    risk_score: float = Field(..., ge=0.0, le=1.0)
    risk_level: RiskLevel
    fraud_hypothesis: str
    signals: list[str]
    model_source: str  # e.g. "xgboost-v1" or "dev-hist-gb" -- always disclosed, never hidden
